--- 
title: "**AA**ir**DS** - Addenbrookes Air Disinfection Study"
author: "Dr Matthew J. Butler"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
output: 
    bookdown::word_document2:
      toc: true
    bookdown::pdf_book:
      extra_dependencies: ["float"]
      keep_tex: true
      pandoc_args: ["--lua-filter=color-text.lua"]
      includes:
        in_header: caption.control.tex
documentclass: book
bibliography: [book.bib, packages.bib, BibliographyAAirDS.bib]
biblio-style: apalike
link-citations: yes
github-repo: git@github.com:mjb302/AAirDS_IAQ_Dataset_JAN-NOV_2022.git
description: "Data analysis for the Addenbrooke's Air Disinfection Study - AAirDS"
header-includes: 
 \usepackage{geometry}
 \geometry{top=0.75in,left=1in,bottom=0.75in,right=0.80in}

---
```{r echo=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  fig.width = 6, 
  fig.height = 3,
  warning = FALSE, 
  message = FALSE,
  echo=FALSE
)
```

```{r eval=FALSE, echo=FALSE}


#Prerequisites
#The following packages are required for the indoor air quality (IAQ) analysis

install.packages("bookdown")
install.packages("downlit")
install.packages("xml2")
install.packages("tinytex")
install.packages("knitr")
install.packages("markdown")
install.packages("rmarkdown")
install.packages("servr")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("lubridate")
install.packages("magrittr")
install.packages("openair")
install.packages("tibble")
install.packages("tidyverse")
install.packages("ggpubr")
install.packages("rstatix")
install.packages("pipeR")
install.packages("mosaicData")
install.packages("timeDate")
install.packages("xts")
#install.packages("yaml")
install.packages("xtable")
install.packages("zoo")
install.packages("timechange")
install.packages("scales")
install.packages("tufte")
install.packages("psych")
install.packages("janitor")
install.packages("corrgram")
install.packages("kableExtra")
install.packages("GPArotation")
install.packages("plotrix")
install.packages("glue")
install.packages("plotly")
install.packages("VIM")
install.packages("mice")
install.packages("reshape2")
```

```{cat, engine.opts = list(file = "color-text.lua")}
Span = function(el)
  color = el.attributes['color']
  -- if no color attribute, return unchange
  if color == nil then return el end
  
  -- transform to <span style="color: red;"></span>
  if FORMAT:match 'html' then
    -- remove color attributes
    el.attributes['color'] = nil
    -- use style attribute instead
    el.attributes['style'] = 'color: ' .. color .. ';'
    -- return full span element
    return el
  elseif FORMAT:match 'latex' then
    -- remove color attributes
    el.attributes['color'] = nil
    -- encapsulate in latex code
    table.insert(
      el.content, 1,
      pandoc.RawInline('latex', '\\textcolor{'..color..'}{')
    )
    table.insert(
      el.content,
      pandoc.RawInline('latex', '}')
    )
    -- returns only span content
    return el.content
  else
    -- for other format return unchanged
    return el
  end
end
```

```{r echo=FALSE}
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

```{r include=FALSE}
# load all the required packages

library(bookdown)
library(downlit)
library(xml2)
library(tinytex)
library(knitr)
library(markdown)
library(rmarkdown)
library(servr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(magrittr)
library(openair)
library(tibble)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(pipeR)
library(mosaicData)
library(timeDate)
library(xts)
library(yaml)
library(xtable)
library(zoo)
library(timechange)
library(scales)
library(tufte)
library(psych)
library(janitor)
library(corrgram)
library(kableExtra)
library(GPArotation)
library(plotrix)
library(glue)
library(plotly)
library(VIM)
library(mice)
library(reshape2)
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(),
  'bookdown', 
  'knitr', 
  'rmarkdown',
  'downlit',
  'xml2',
  'tinytex',
  'markdown',
  'servr',
  'dplyr',
  'ggplot2',
  'lubridate',
  'magrittr',
  'openair',
  'tibble',
  'ggpubr',
  'rstatix',
  'pipeR',
  'mosaicData',
  'timeDate',
  'xts',
  'yaml',
  'xtable',
  'zoo',
  'timechange',
  'scales',
  'psych',
  'janitor',
  'corrgram',
  'kableExtra',
  'GPArotation',
  'plotrix',
  'glue',
  'plotly',
  'VIM',
  'mice'), 
  'packages.bib')
```

```{r output}

rungraphs <- FALSE # if TRUE runs all the code to generate graphs i.e. if the original data is changed.
rungraphs2 <- FALSE
picturesonly <- TRUE # if TRUE only imports the figures generated from a previous render_book() index.html
xts <- TRUE # if true generates all the xts objects
loadenvironment <- FALSE
loadstats <- FALSE
runtables = TRUE
tablesAspictures = FALSE

# here is the code to render a pdf in LaTex: "render_book(output_format = pdf_book(pandoc_args="--lua-filter=color-text.lua"))"
# and without TOCs "render_book(output_format = pdf_book(toc = FALSE, pandoc_args="--lua-filter=color-text.lua"))"
```
